//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewsReader.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewsReader.Resources.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bookmark.
        /// </summary>
        public static string bookmark {
            get {
                return ResourceManager.GetString("bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string btn_add_rss {
            get {
                return ResourceManager.GetString("btn_add_rss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add RSS feed.
        /// </summary>
        public static string btn_add_rss_tooltip {
            get {
                return ResourceManager.GetString("btn_add_rss_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btn_cancel {
            get {
                return ResourceManager.GetString("btn_cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string btn_cancel_tooltip {
            get {
                return ResourceManager.GetString("btn_cancel_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string btn_delete_rss {
            get {
                return ResourceManager.GetString("btn_delete_rss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete RSS feed.
        /// </summary>
        public static string btn_delete_rss_tooltip {
            get {
                return ResourceManager.GetString("btn_delete_rss_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string btn_edit_rss {
            get {
                return ResourceManager.GetString("btn_edit_rss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit RSS feed.
        /// </summary>
        public static string btn_edit_rss_tooltip {
            get {
                return ResourceManager.GetString("btn_edit_rss_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a new link to the RSS feed:.
        /// </summary>
        public static string dialog_add_text {
            get {
                return ResourceManager.GetString("dialog_add_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the following RSS feed?.
        /// </summary>
        public static string dialog_delete_text {
            get {
                return ResourceManager.GetString("dialog_delete_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the link to the RSS feed:.
        /// </summary>
        public static string dialog_edit_text {
            get {
                return ResourceManager.GetString("dialog_edit_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link:.
        /// </summary>
        public static string dialog_link {
            get {
                return ResourceManager.GetString("dialog_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter or edit the link.
        /// </summary>
        public static string dialog_link_tooltip {
            get {
                return ResourceManager.GetString("dialog_link_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title:.
        /// </summary>
        public static string dialog_title {
            get {
                return ResourceManager.GetString("dialog_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter or edit the title.
        /// </summary>
        public static string dialog_title_tooltip {
            get {
                return ResourceManager.GetString("dialog_title_tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last update:.
        /// </summary>
        public static string last_update {
            get {
                return ResourceManager.GetString("last_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string news {
            get {
                return ResourceManager.GetString("news", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No bookmarks available.
        /// </summary>
        public static string no_bookmark {
            get {
                return ResourceManager.GetString("no_bookmark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data available.
        /// </summary>
        public static string no_data {
            get {
                return ResourceManager.GetString("no_data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string settings {
            get {
                return ResourceManager.GetString("settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string settings_categories {
            get {
                return ResourceManager.GetString("settings_categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string settings_language {
            get {
                return ResourceManager.GetString("settings_language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RSS-Feeds.
        /// </summary>
        public static string settings_rss {
            get {
                return ResourceManager.GetString("settings_rss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Career.
        /// </summary>
        public static string theme_career {
            get {
                return ResourceManager.GetString("theme_career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cultural.
        /// </summary>
        public static string theme_cultural {
            get {
                return ResourceManager.GetString("theme_cultural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Economy.
        /// </summary>
        public static string theme_economy {
            get {
                return ResourceManager.GetString("theme_economy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        public static string theme_general {
            get {
                return ResourceManager.GetString("theme_general", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Health.
        /// </summary>
        public static string theme_health {
            get {
                return ResourceManager.GetString("theme_health", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to International.
        /// </summary>
        public static string theme_international {
            get {
                return ResourceManager.GetString("theme_international", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Politics.
        /// </summary>
        public static string theme_politics {
            get {
                return ResourceManager.GetString("theme_politics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sport.
        /// </summary>
        public static string theme_sport {
            get {
                return ResourceManager.GetString("theme_sport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology.
        /// </summary>
        public static string theme_technology {
            get {
                return ResourceManager.GetString("theme_technology", resourceCulture);
            }
        }
    }
}
